live:
- name: Ethereum
  networks:
  - chainid: 1
    explorer: https://api.etherscan.io/api
    host: https://lb.drpc.org/ogrpc?network=ethereum&dkey=$DRPC_DKEY
    id: mainnet
    name: Mainnet
- name: Arbitrum
  networks:
  - chainid: 42161
    explorer: https://api.arbiscan.io/api
    host: https://lb.drpc.org/ogrpc?network=arbitrum&dkey=$DRPC_DKEY

    id: arbitrum-main
    multicall2: '0x5B5CFE992AdAC0C9D48E05854B2d91C73a003858'
    name: Mainnet
- name: Optimism
  networks:
  - chainid: 10
    explorer: https://api-optimistic.etherscan.io/api
    host: https://lb.drpc.org/ogrpc?network=optimism&dkey=$DRPC_DKEY
    id: optimism-main
    name: Mainnet
development:
  - name: Hardhat (Mainnet Fork)
    id: hardhat-fork-curve
    cmd: npx hardhat node
    host: http://127.0.0.1
    timeout: 500
    cmd_settings:
      accounts: 10
      evm_version: shanghai
      fork: mainnet
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
  - name: Hardhat (Arbitrum Fork)
    id: arbitrum-fork
    cmd: npx hardhat node
    host: http://127.0.0.1
    timeout: 500
    cmd_settings:
      accounts: 10
      evm_version: london
      fork: arbitrum-main
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
  - name: Hardhat (Optimism Fork)
    id: optimism-fork
    cmd: npx hardhat node
    host: http://127.0.0.1
    timeout: 500
    cmd_settings:
      accounts: 10
      evm_version: shanghai
      fork: optimism-main
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
